### ISSUE TITLE
Video doesn't work in Safari

### ISSUE THREAD

**Issue by nskobelevs** [ProstoSanja/place-2022#9]
As usual, Safari is behind other browsers - it currently doesn't support `.webm` videos so your website just has the gray background when viewed on Safari.

Minuscule but thought you might want to know!

**Comment by ProstoSanja** [comment]
Hey, thanks, Ill get on it. Is this mac or mobile safari?

**Comment by nskobelevs** [comment]
Neither work unfortunately.

[Can I use](https://caniuse.com/?search=webm) says partial support on desktop with a minimum version. I updated mine recently enough but I'll double check versions tomorrow.

I'd say easiest fix might be to add multiple sources to the video tag?

**Comment by ProstoSanja** [comment]
yeah, That's what ill do

**Comment by ProstoSanja** [comment]
will have to wait until tomorrow

**Comment by nskobelevs** [comment]
MacOS 12.3 - Safari 15.4
iOS 15.4.1 - Safari 15.4 

TIL iOS safari version always matches the iOS version since it's part of the OS

**Comment by ProstoSanja** [comment]
Should be fixed in 5224d92, and deployed within hour

**Comment by nskobelevs** [comment]
Just double checked there and sadly still not showing.
I ended up cloning the repo since it was weird that is wasn't loading.

It works if the mp4 source is first but that kinda defeats the purpose of having a webm one in the first place.

My guess is because Safari technically has _partial_ support it doesn't ignore the webm source and still tries to play it even if it can't

**Comment by ProstoSanja** [comment]
I will investigate

**Comment by nskobelevs** [comment]
Lemme know if you want me to test anything locally before you deploy it!

**Comment by nskobelevs** [comment]
Weirdly, now it works in mobile Safari but not Desktop 🤔 Would expect them to at least be consistent
